### PR TITLE
Adds 4.1.0 for enterprise edition

### PR DESCRIPTION
**Pull request by Chippiewill**
Untested thus far.

### CODE REVIEW

**Comment by Chippiewill** [comment]
Tested. It build and runs.

**Comment by tleyden** [comment]
@Chippiewill do you have access to the dockerhub account or do you need @ceejatec or myself to create a new build there?

**Comment by Chippiewill** [comment]
I don't have access so if you could create the build that would be great :)

**Comment by tleyden** [comment]
@Chippiewill I kicked it off .. see https://hub.docker.com/r/couchbase/server/tags/

**Pull request merged**
