### PR TITLE
CBD-5970 support building couchbase-columnar docker image.

### PR DESCRIPTION
**Pull request by mhocouchbase**
add template for generating couchbase-columnar docker images.

-Ming

### CODE REVIEW

**Review by ceejatec — COMMENTED** [review]
Do you think the intent is that couchbase-columnar and couchbase-server Dockerfiles will always be 'identical'? If not, then I think we should take this opportunity to clean up a few things in columnar's Dockerfile.template that are unnecessary / undesirable.

**Review by ceejatec — COMMENTED** [review]
Also, not strictly related to this change but relevant: it's still using Ubuntu 20.04 for all 7.x and newer images, it appears, and this would include Columnar. That's almost certainly Bad(tm). We should extend ubuntuVersion().

**Comment by mhocouchbase** [comment]
> Do you think the intent is that couchbase-columnar and couchbase-server Dockerfiles will always be 'identical'? If not, then I think we should take this opportunity to clean up a few things in columnar's Dockerfile.template that are unnecessary / undesirable.

I am not sure how different they will be in the future.  Currently, the only difference is ns_server's config profile and deb package itself.  Any suggestion on what should be cleaned up?

**Comment by ceejatec** [comment]
Three things jump out that should be irrelevant for couchbase-columnar:

1. The comment around .SYSTEMD_WORKAROUND.
2. The curl.real check.
3. Probably a bunch of those ports don't need to be exposed for columnar.

Still, from what I hear, for now at least this Docker image is just intended for internal use and debugging, so those are minor points. I'll file a separate ticket for some cleanups and another one for the Ubuntu base image fix, and approve this change.

**Review by ceejatec — APPROVED** [review]

**Comment by mhocouchbase** [comment]
> Three things jump out that should be irrelevant for couchbase-columnar:
> 
> 1. The comment around .SYSTEMD_WORKAROUND.
> 2. The curl.real check.
> 3. Probably a bunch of those ports don't need to be exposed for columnar.
> 
> Still, from what I hear, for now at least this Docker image is just intended for internal use and debugging, so those are minor points. I'll file a separate ticket for some cleanups and another one for the Ubuntu base image fix, and approve this change.

Cool.  I made one change to let columnar use ubuntu:24.04.
I started working on the base image version fix.  Will verify all the dockerfiles before proposing a PR.  Please let me know if you have already filed a ticket.  I can use it for the PR.

**Pull request merged**
