### PR TITLE
Changes to the readme.md for lining up with tech docs and correct links on the couchbase.com side. 

### PR DESCRIPTION
**Pull request by cihanb**

### CODE REVIEW

**Comment by ceejatec** [comment]
Unfortunately it does not appear that the Official Docker docs can include any images except the logo.png. If we want other images in the doc, we will need to host them elsewhere.

**Comment by tleyden** [comment]
This PR should get squashed into a single commit so we don't pollute the commit history.  Github has the ability to enable "squashed merges" -- @ceejatec can you check the settings?  I don't have access.

**Comment by tleyden** [comment]
@cihanb looks like there is still a reference to the `couchbase/server` container:

```
docker run couchbase/server:community-4.0.0
```

**Comment by ceejatec** [comment]
@tleyden Squash commits are allowed for this repo. It appears that to you select which you want (merge or squash) in a drop-down menu on the "Confirm merge" button here on the PR (which appears after clicking the green "Merge pull request" button).

**Comment by tleyden** [comment]
Great!

**Comment by cihanb** [comment]
I am updating a few TODO links once documentation deploys the docker pages. Should be before EOD today.

**Comment by cihanb** [comment]
For the images, I made the references directly to this repo and with raw links. We should be ok referring to the github links.

**Comment by ceejatec** [comment]
Are you all done pushing changes, Cihan?

**Comment by cihanb** [comment]
the pull request is complete now

**Comment by ceejatec** [comment]
I'm merging this as-is for now, and will work on splitting it into the form required for the Official Docker image. I will push any tweaks back here.

**Pull request merged**
