### PR TITLE
Add SGW 2.1.0-devbuild

### PR DESCRIPTION
**Pull request by bbrks**
### `sync-gateway:2.1.0-devbuild`
- Adds `sync-gateway:2.1.0-devbuild-community`
- Adds `sync-gateway:2.1.0-devbuild-enterprise`
- Updates default config to adopt new logging changes in 2.1.0
- Passes through `--defaultLogFilePath` argument to Sync Gateway command for 2.1.0

### TODO
- [x] Create SGW builds after above PR merged
- [x] Upload builds to cbmobile-packages s3 bucket
- [x] Change build numbers in `generate.go` in this PR

### CODE REVIEW

**Comment by tleyden** [comment]
Since you changed generate/resources/sync-gateway/scripts/entrypoint.sh, I'm surprised that files like https://github.com/couchbase/docker/blob/master/enterprise/sync-gateway/2.0.0-devbuild/scripts/entrypoint.sh weren't changed (or did you just not commit them?)

I can't remember how this tool works.. but I thought it would change all instances for all versions.  That doesn't necessarily break things, but if the docker images were rebuilt then it probably would break things.

Maybe this tool should take some parameters on the version(s) that should be regenerated.

**Comment by bbrks** [comment]
It changed all of them, but I only committed the 2.1.0 directories, as that change should not be in older versions

**Comment by ceejatec** [comment]
We can't commit this as-is, then. The next time any of us runs the generator script, it'll modify all the entrypoint.sh scripts for all images.

We can't commit just the devbuild entrypoint.sh scripts either, or else the next time we run the generator script those changes will get overwritten.

I guess Traun is right - we'll need to make the generator script more intelligent in some way. We could make it take a parameter to specify which version to regenerate, but IMHO that would be error-prone; if we forgot to specify that parameter it would still overwrite everything. Ideally the script itself would be intelligent enough to know how to generate all the versions, I guess? There's some precedent for that on the couchbase-server side of things; it selects a different base image depending on product version, for instance.

**Comment by bbrks** [comment]
Yeah agreed. I'll close this PR and think about how we can solve the versioning problem first. This isn't needed urgently anyway.

**Comment by tleyden** [comment]
@ceejatec any chance you'd be willing to update https://github.com/couchbase/docker/issues/100 and sketch out a "branch based approach" and point to some examples?  I remember you mentioned that there was an overall approach that leveraged branches rather than directories.  

I think at the very least we should open the conversation.

**Comment by tleyden** [comment]
@bbrks for your case, what's been happening so far is that things are regenerated and pushed up to github, but the docker images are not rebuilt on dockerhub by default, and so that old images (with the old scripts) haven't been updated with the new (broken) dockerfiles.

It's very brittle and not ideal.

**Pull request closed without merging**
