### PR TITLE
Add Couchbase Server 4.5.0-DP1

### PR DESCRIPTION
**Pull request by Chippiewill**

### CODE REVIEW

**Comment by ceejatec** [comment]
Hey, thanks - I assume you created those files by running the generate.go script?

**Comment by Chippiewill** [comment]
yeah

**Comment by ceejatec** [comment]
Thanks again.

**Comment by tleyden** [comment]
Aren't there new ports in 4.5?

**Comment by ceejatec** [comment]
First I've heard of that, Traun - good thing we have these DP things. :)

Who do you think would know that for sure?

**Comment by Chippiewill** [comment]
Looks like FTS needs port 9110.

**Comment by tleyden** [comment]
@steveyen is exposing port 9110 enough for FTS?

**Comment by tleyden** [comment]
Just spoke to @steveyen who mentioned that port 9110 may be changing.

**Comment by steveyen** [comment]
Looks like it's going to change to port 8094 soon... https://issues.couchbase.com/browse/MB-18065

**Comment by ceejatec** [comment]
I raised #31 , please take a look.

**Pull request merged**
