### PR TITLE
Do not set global LD_LIBRARY_PATH to fix curl

### LINKED ISSUE #13: Curl does not work in Ubuntu 12.04 container
I am trying to get around https://github.com/couchbase/docker/issues/12

By using the REST API rather then couchbase-cli

How ever when ever I use curl in the container I get "curl: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory"

It seems their are two solutions one install updated curl from "ppa:costamagnagianfranco/ettercap-stable-backports"

Or rebase the container on either Debian 7 or Ubuntu 14.04

I would be happy to issue a PR for either option.

### PR DESCRIPTION
**Pull request by avsej**
This is more granular attempt to fix #13

### CODE REVIEW

**Comment by ceejatec** [comment]
Thanks for the suggestion. I'm going to propose a different solution since I'm uncomfortable with this one - I don't like that it leaves /opt/couchbase/bin/curl still non-functional without LD_LIBRARY_PATH. Stay tuned!

**Comment by ceejatec** [comment]
Take a look at #41 and see what you think.

**Comment by tleyden** [comment]
Why do we even need to use a bundled curl rather than just installing the curl package?

**Comment by avsej** [comment]
in this case there will be two curls, an curl will also pull lots of deps (which already in couchbase). So image goes bigger with no reason

Probably question would be "why do we package curl into the application, while we could just use it from system?". It is not a libcurl dependency, we bundle whole executable

**Comment by tleyden** [comment]
> Probably question would be "why do we package curl into the application, while we could just use it from system?"

I guess it is being called via `exec` rather than via `libcurl`, and it's bundled so that it works on every linux distro.  

@mcpaddy any idea where curl is being used?  is it only for cbcollectinfo?

**Comment by avsej** [comment]
curl is pretty portable, maybe it make sense to try to use system curl, if server does not use libcurl.

**Comment by ceejatec** [comment]
Command-line curl is used by cbcollect_info, yes, so it makes sense to include it in the distribution IMHO. In the past I think it was even more important because curl was also used for uploading logs to our server, which required https: that we couldn't always depend on the system-provided curl to support. I'm not sure if that's still relevant.

**Comment by tleyden** [comment]
> Command-line curl is used by cbcollect_info

`cbcollect_info` is written in python, which has a great "batteries included" http client library.  I'm curious why `curl` was chosen over just using the built-in python http client lib.

**Pull request closed without merging**
