### PR TITLE
#78: Allow container to run as non-root user

### LINKED ISSUE #78: Unable to start couchbase when running container with a non user
HI,
I'm getting the following status when tryi,g to run couchbase container with a non root  user:

`runsvdir -P /etc/service log: -server: fatal: unable to open supervise/lock: file does not exist runsv couchbase-server: fatal: unable to open supervise/lock: fi`

I know the entrypoint must be called using a root user, but we have a constraint not running container as a root user.
Is there any way/workaround for this?
Thanks

### PR DESCRIPTION
**Pull request by ceejatec**
Fixes #78

### CODE REVIEW

**Comment by tleyden** [comment]
@ceejatec looks good to me!

Btw if you add "Fixes #78" to the ticket, it will close the [upstream issue](https://github.com/couchbase/docker/issues/78).  Also it's usually a good idea to at least link to the original issue for reference.

Also, regarding QE signoff, how about we merge and push to dockerhub `couchbase/server`, and allow QE to review before it gets pushed to the official image repo?

Also, @Zizou84 and any other interested parties would have a chance to easily QA it by pulling from dockerhub.

**Comment by ceejatec** [comment]
I did have "#78:" in my commit message, which was at least enough to have my commit to my fork show up on the ticket - but apparently not enough for this PR to show up there, which is kind of weird. Anyway.

I think I'll do what you suggest, regarding couchbase vs. couchbase/server. However, the timing is bad since we need to push out a new official version (5.0.1) today. So the official update will likely have to wait until 5.0.2.

**Comment by tleyden** [comment]
@ceejatec there are conflicts, so I think you need to rebase your PR off the latest master commit.  Looks like you might have based your changes on an older commit.

**Comment by ceejatec** [comment]
I rebased this change, and fixed a couple typos / bad formatting in the README and entrypoint script. Merging now.

**Pull request merged**
