### PR TITLE
Switch to runit, don't let couchbase run as pid 1

### PR DESCRIPTION
**Pull request by hookenz**
This pull request is born out of frustration running this container (in particular under CoreOS).  Nearly always after a view was loaded or a document was added, a bucket on a node would be shut down and the server process "beam" would go into high CPU usage.   Rebalancing would fail with "badmatch" errors.

The  issue is filed under here: [MB-15114] (https://issues.couchbase.com/browse/MB-15114)

##### Summary:
I could not run our workloads passed 2 days despite there being hardly any documents or views loaded.  It ran longer with a single node.  Strangely, it might appear to run error free on one server, but always one particular node would trip up.  In that particular case I ended up failing over the bad server and rebalancing with a single node.  I switched off the replicas.  It ran for 2-3 days then collapsed into a heap.  The errors were captured and attached in the original issue I think.
It didn't matter what content was loaded.  I was able to reproduce this with even by loading the 2 samples after a fresh install 2 server cluster.

I should point out that the original container (including the more recent gosu version) would do this under bare metal or on Amazon EC2.  On bare metal it was better.  But I had one particular node that kept failing and when I moved that server process to a different physical machine (identical hardware) the problem went away.  On EC2, the issue cropped up frequently.

None of these problems were seen when running the server outside of docker obviously.
In terms of environmental differences, docker normally doesn't run an init system.  And so the Couchbase server would run as PID 1. as they are placed into their own process name space.  PID 1 processes need to do a bit more work if they fork child processes.  Couchbase forks child processes, so based on a hunch, I created this fork of https://github.com/couchbase/docker

##### What's different?
1. Switch the Couchbase server to run under the lightweight [runit](http://smarden.org/runit/) init system instead of attempting to run the couchbase-server as PID 1.  This has the benefit of restarting the server if it was ever end pre-maturely.

2. Switch the the docker Ubuntu 12.04 docker base.  Mainly because it's more mature and lighter weight.  You can run the docker image on top of CoreOS or CentOS if you choose though.

##### Results:
I've been running stably for several weeks now with load.  

I've also run this updated version on the nodes that I previously saved and marked as dead.  They now run OK, but slow as they were m3.large (dual core only).

Although it runs on m3.large EC2 instances it's slow because these are dual core.  It should really be run on EC2 m3.xlarge as a minimum.   So for production that's what I'm currently using with 3-server configuration.

### CODE REVIEW

**Comment by tleyden** [comment]
@hookenz thanks for this contribution.  I've been meaning to test this and get back to you.

By the way [this article](http://sirupsen.com/production-docker/) has an interesting section that may be relevant.  Search for "A container runs in a PID namespace"

**Comment by hookenz** [comment]
@tleyden - Looks like moves are afoot to fix the problem.   https://github.com/docker/docker/issues/11529   Might be available in docker 1.9?

**Comment by ceejatec** [comment]
Apologies for not following up on this contribution earlier. Thanks very much for taking the time!

I'm going to explore the changes more in depth tonight, but do you have any idea why the changes you made are working? In particular, I'm curious about runit. I have had problems in other docker containers running a "bash" script as process 1 due to bash not reaping children and leading to the zombie apocalypse. But I didn't think that would be a problem with couchbase-server running as the base. Did you see zombies being formed? If not, what led you to trying runit?

**Comment by hookenz** [comment]
@ceejatec - I actually thought bash was capable of reaping children?  I read about it in a blog, that may have been wrong.  

The PID 1 problem is why https://github.com/phusion/baseimage-docker came about.  Personally I feel it's the wrong approach, but it raised the PID 1 issue which appears to now be getting some attention and may be fixed in a later version of docker.

runit fixes this because it reaps children correctly.  So does the other alternative called supervisor.  I prefer the lighter weight runit and use it on every container now that has apps that fork children.

**Comment by ceejatec** [comment]
@hookenz - ah, no, you're correct - bash's problem isn't reaping, it's signal handling. Either way, it's not an appropriate PID 1.

FWIW, I agree with you that baseimage-docker isn't the right approach to Dockerization in most cases.

So were you seeing zombies in your usage of the original Couchbase image? Was that what led to using runit?

**Comment by ceejatec** [comment]
I've locally smoke-tested these changes, and I like them. I did find one important problem (not in the PR itself, but revealed by it) that needs to be fixed, but I think it'll be easiest to merge this and then push a fix.

Thank you very much for taking the time to make this change, and for reporting your testing results!

**Comment by hookenz** [comment]
@ceejatec - Awesome.  That's for reviewing my changes, I'm glad you like them.  I've just noted that the README.md refers to CentOS as the containing OS which should probably be changed to Ubuntu 12.04.

The fix to this for us was out of necessity really.  We're actually crazy enough to be running this in production!  It is working very well now.

**Comment by tleyden** [comment]
Cool!

**Pull request merged**
